mgmt:
  interface: GigabitEthernet0/5
  ip: 172.16.99.11
  mask: 255.255.255.0
  description: MGMT

ospf_router_id: 1.1.1.1

routed_interfaces:
  - name: GigabitEthernet0/0
    ip: 10.0.1.1
    mask: 255.255.255.252
    description: to_R2
    enabled: true
  - name: GigabitEthernet0/1
    ip: 10.0.4.1
    mask: 255.255.255.252
    description: to_R3
    enabled: true
  - name: GigabitEthernet0/4
    ip: 10.0.5.1
    mask: 255.255.255.252
    description: to_R4
    enabled: true
  - name: Loopback0
    ip: 1.1.1.1
    mask: 255.255.255.255
    description: R1_Loopback0
    enabled: true

ospf_networks:
  - { network: "10.0.1.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "10.0.4.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "10.0.5.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "1.1.1.1", wildcard: "0.0.0.0", area: 0 }

ospf_passive_interfaces: []
