mgmt:
  interface: FastEthernet3/1
  ip: 172.16.99.12
  mask: 255.255.255.0
  description: MGMT

ospf_router_id: 2.2.2.2

routed_interfaces:
  - name: FastEthernet0/0
    ip: 10.0.1.2
    mask: 255.255.255.252
    description: TRANSIT (was Vlan10)
    enabled: true
  - name: FastEthernet2/0
    ip: 10.0.2.1
    mask: 255.255.255.252
    description: TRANSIT (was Vlan20)
    enabled: true

ospf_networks:
  - { network: "10.0.1.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "10.0.2.0", wildcard: "0.0.0.3", area: 0 }

ospf_passive_interfaces: []

