mgmt:
  interface: GigabitEthernet0/5
  ip: 172.16.99.14
  mask: 255.255.255.0
  description: MGMT

ospf_router_id: 4.4.4.4

routed_interfaces:
  - name: GigabitEthernet0/2
    ip: 10.0.3.2
    mask: 255.255.255.252
    description: to_R3
    enabled: true
  - name: GigabitEthernet0/3
    ip: 10.0.2.2
    mask: 255.255.255.252
    description: to_R2
    enabled: true
  - name: GigabitEthernet0/4
    ip: 10.0.5.2
    mask: 255.255.255.252
    description: to_R1
    enabled: true
  - name: Loopback0
    ip: 4.4.4.4
    mask: 255.255.255.255
    description: R4_Loopback0
    enabled: true

ospf_networks:
  - { network: "10.0.5.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "10.0.2.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "10.0.3.0", wildcard: "0.0.0.3", area: 0 }
  - { network: "4.4.4.4", wildcard: "0.0.0.0", area: 0 }

ospf_passive_interfaces: []
