[ios]
R1 ansible_host=172.16.99.11
R2 ansible_host=172.16.99.12

[ios:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios

ansible_user=admin
ansible_password=admin

# If your routers require enable mode for config changes, set these too.
# If they don't, you can leave them commented.
ansible_become=yes
ansible_become_method=enable
ansible_become_password=admin
