frr defaults traditional
hostname r2
!
interface lo
 ip address 2.2.2.2/32
!
interface eth1
 ip address 10.0.1.2/29
!
interface eth2
 ip address 10.0.2.2/29
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.1.1 remote-as 65001
 neighbor 10.0.1.1 description bgp_to_r1
 neighbor 10.0.2.3 remote-as 65003
 neighbor 10.0.2.3 description bgp_to_r3
 address-family ipv4 unicast
  network 2.2.2.2/32
  network 10.0.1.0/29
  network 10.0.2.0/29
 exit-address-family
!
line vty
