---
- name: Deploy SNMPv3 configuration to IOSv routers
  hosts: routers
  gather_facts: false

  tasks:
    - name: Configure SNMPv3
      cisco.ios.ios_config:
        src: templates/snmp.j2

    - name: Collect SNMP group
      cisco.ios.ios_command:
        commands:
          - show snmp group
      register: snmp_group

    - name: Display SNMP group
      ansible.builtin.debug:
        var: snmp_group.stdout_lines

    - name: Collect SNMP user
      cisco.ios.ios_command:
        commands:
          - show snmp user
      register: snmp_user

    - name: Display SNMP user
      ansible.builtin.debug:
        var: snmp_user.stdout_lines

    - name: Collect SNMP host
      cisco.ios.ios_command:
        commands:
          - show snmp host
      register: snmp_host

    - name: Display SNMP host
      ansible.builtin.debug:
        var: snmp_host.stdout_lines

    - name: Collect SNMP ACL
      cisco.ios.ios_command:
        commands:
          - show ip access-lists SNMP_ACL
      register: snmp_acl

    - name: Display SNMP ACL
      ansible.builtin.debug:
        var: snmp_acl.stdout_lines

    - name: Assert MONITORING group is present
      ansible.builtin.assert:
        that:
          - "'MONITORING' in snmp_group.stdout[0]"
        fail_msg: "SNMPv3 group MONITORING not found"
        success_msg: "SNMPv3 group MONITORING is configured"

    - name: Assert trap host is configured
      ansible.builtin.assert:
        that:
          - snmp_trap_destination in snmp_host.stdout[0]
        fail_msg: "SNMP trap host {{ snmp_trap_destination }} not found"
        success_msg: "SNMP trap host {{ snmp_trap_destination }} is configured"
