- name: Deploy eBGP configuration to IOSv routers
  hosts: routers
  gather_facts: false
 
  tasks:
    - name: Configure interfaces
      cisco.ios.ios_config:
        src: templates/interfaces.j2
 
    - name: Configure BGP
      cisco.ios.ios_config:
        src: templates/bgp.j2
 
