frr defaults traditional
hostname r3
!
interface lo
 ip address 3.3.3.3/32
!
interface eth1
 ip address 10.0.2.3/29
!
interface eth2
 ip address 10.0.3.3/29
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 neighbor 10.0.2.2 remote-as 65002
 neighbor 10.0.2.2 description bgp_to_r2
 neighbor 10.0.3.4 remote-as 65004
 neighbor 10.0.3.4 description bgp_to_r4
 address-family ipv4 unicast
  network 3.3.3.3/32
  network 10.0.2.0/29
  network 10.0.3.0/29
 exit-address-family
!
line vty
