frr defaults traditional
hostname r4
!
interface lo
 ip address 4.4.4.4/32
!
interface eth1
 ip address 10.0.3.4/29
!
interface eth2
 ip address 10.0.4.4/29
!
interface eth3
 ip address 10.0.6.4/29
!
router bgp 65004
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 neighbor 10.0.3.3 remote-as 65003
 neighbor 10.0.3.3 description bgp_to_r3
 neighbor 10.0.4.1 remote-as 65001
 neighbor 10.0.4.1 description bgp_to_r1
 neighbor 10.0.6.5 remote-as 65100
 neighbor 10.0.6.5 description bgp_to_k3s_metallb
 address-family ipv4 unicast
  network 4.4.4.4/32
  network 10.0.3.0/29
  network 10.0.4.0/29
  network 10.0.6.0/29
 exit-address-family
!
line vty
